import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

// A clean, editable rate-confirmation copy generated from structured data.
// This is a LoadSprint-formatted restatement of the load's key terms — the
// original broker PDF is always kept separately.
export type ConfirmationStop = { address: string; time?: string };
export type ConfirmationData = {
  ref?: string;
  rate?: number;
  brokerName?: string;
  brokerContact?: string; // email / phone / address on one line
  billTo?: string;
  carrierName?: string; // the dispatcher's company
  driverName?: string;
  pickups: ConfirmationStop[];
  dropoffs: ConfirmationStop[];
  notes?: string;
  dateLabel?: string; // e.g. "Jul 8, 2026"
};

export async function generateConfirmationPdf(d: ConfirmationData): Promise<string> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]); // US Letter
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();

  const navy = rgb(0.04, 0.09, 0.16);
  const sky = rgb(0.05, 0.58, 0.53); // teal, matching the app
  const gray = rgb(0.42, 0.47, 0.53);
  const line = rgb(0.85, 0.88, 0.92);
  const M = 54;

  const wrap = (s: string, max: number) => (s.length > max ? s.slice(0, max - 1) + "…" : s);
  let y = height - 60;

  // Header
  page.drawText("LoadSprint", { x: M, y, size: 22, font: bold, color: sky });
  page.drawText("RATE CONFIRMATION", { x: width - M - 168, y: y + 2, size: 12, font: bold, color: navy });
  y -= 15;
  page.drawText("Confirmation copy", { x: M, y, size: 10, font, color: gray });
  if (d.dateLabel)
    page.drawText(d.dateLabel, { x: width - M - 168, y, size: 9.5, font, color: gray });
  y -= 20;
  page.drawLine({ start: { x: M, y }, end: { x: width - M, y }, thickness: 1, color: line });
  y -= 28;

  // Ref + rate row
  page.drawText(`Load ${d.ref || "—"}`, { x: M, y, size: 17, font: bold, color: navy });
  if (typeof d.rate === "number" && d.rate > 0) {
    const rateStr = `$${Math.round(d.rate).toLocaleString("en-US")}`;
    const w = bold.widthOfTextAtSize(rateStr, 22);
    page.drawText("CARRIER RATE", { x: width - M - Math.max(w, 120), y: y + 20, size: 8.5, font: bold, color: gray });
    page.drawText(rateStr, { x: width - M - w, y, size: 22, font: bold, color: sky });
  }
  y -= 30;

  // Parties — two columns
  const col2 = width / 2 + 6;
  const partyBlock = (x: number, title: string, lines: string[]) => {
    let yy = y;
    page.drawText(title, { x, y: yy, size: 8.5, font: bold, color: gray });
    yy -= 15;
    for (const ln of lines.filter(Boolean)) {
      page.drawText(wrap(ln, 46), { x, y: yy, size: 10, font, color: navy });
      yy -= 14;
    }
    return yy;
  };
  const leftEnd = partyBlock(M, "BROKER / BILL TO", [
    d.brokerName || d.billTo || "—",
    d.brokerContact || "",
    d.billTo && d.brokerName && d.billTo !== d.brokerName ? `Bill to: ${d.billTo}` : "",
  ]);
  const rightEnd = partyBlock(col2, "CARRIER / DRIVER", [
    d.carrierName || "—",
    d.driverName ? `Driver: ${d.driverName}` : "",
  ]);
  y = Math.min(leftEnd, rightEnd) - 14;

  // Stops
  const drawStops = (title: string, stops: ConfirmationStop[]) => {
    page.drawText(title, { x: M, y, size: 11, font: bold, color: navy });
    y -= 17;
    if (stops.length === 0) {
      page.drawText("—", { x: M + 6, y, size: 10, font, color: gray });
      y -= 16;
      return;
    }
    stops.forEach((s, i) => {
      if (y < 110) return;
      page.drawText(`${i + 1}.`, { x: M + 2, y, size: 10, font: bold, color: sky });
      page.drawText(wrap((s.address || "").replace(/\s+/g, " "), 74), { x: M + 20, y, size: 10, font, color: navy });
      y -= 13;
      if (s.time) {
        page.drawText(wrap(s.time, 60), { x: M + 20, y, size: 8.5, font, color: gray });
        y -= 12;
      }
      y -= 3;
    });
  };
  drawStops(`Pickups (${d.pickups.length})`, d.pickups);
  y -= 6;
  drawStops(`Deliveries (${d.dropoffs.length})`, d.dropoffs);

  // Notes
  if (d.notes && d.notes.trim() && y > 130) {
    y -= 8;
    page.drawText("Notes", { x: M, y, size: 11, font: bold, color: navy });
    y -= 15;
    const words = d.notes.replace(/\s+/g, " ").trim().split(" ");
    let lineStr = "";
    for (const w of words) {
      if ((lineStr + " " + w).length > 92) {
        page.drawText(lineStr, { x: M, y, size: 9.5, font, color: navy });
        y -= 13;
        lineStr = w;
        if (y < 90) break;
      } else lineStr = lineStr ? lineStr + " " + w : w;
    }
    if (lineStr && y > 80) page.drawText(lineStr, { x: M, y, size: 9.5, font, color: navy });
  }

  // Footer
  page.drawLine({ start: { x: M, y: 60 }, end: { x: width - M, y: 60 }, thickness: 1, color: line });
  page.drawText("Generated by LoadSprint — a clean copy of the broker rate confirmation. Original is kept on file.", {
    x: M,
    y: 46,
    size: 8,
    font,
    color: gray,
  });

  const bytes = await pdf.save();
  return `data:application/pdf;base64,${Buffer.from(bytes).toString("base64")}`;
}
