import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Load } from "@/lib/loads";

// Build a clean one-page "Driver Rate Sheet" PDF showing the pay the dispatcher
// set for the driver, plus the load reference and stops. Returned as a base64
// data URL so it can be stored as a load document.
export async function generateDriverRateSheet(load: Load, rate: number): Promise<string> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]); // US Letter
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const { height } = page.getSize();

  const navy = rgb(0.04, 0.09, 0.16);
  const sky = rgb(0.22, 0.74, 0.97);
  const gray = rgb(0.42, 0.47, 0.53);
  const line = rgb(0.85, 0.88, 0.92);

  const M = 56;
  let y = height - 64;

  // Header
  page.drawText("LoadSprint", { x: M, y, size: 24, font: bold, color: sky });
  y -= 16;
  page.drawText("Driver Rate Sheet", { x: M, y, size: 12, font, color: gray });
  y -= 30;
  page.drawLine({ start: { x: M, y }, end: { x: 612 - M, y }, thickness: 1, color: line });
  y -= 34;

  // Load reference + driver
  page.drawText(`Load ${load.ref || load.id}`, { x: M, y, size: 18, font: bold, color: navy });
  y -= 24;
  if (load.driverName) {
    page.drawText(`Driver: ${load.driverName}`, { x: M, y, size: 11, font, color: navy });
    y -= 30;
  } else {
    y -= 6;
  }

  // Pay box
  page.drawRectangle({
    x: M,
    y: y - 60,
    width: 612 - M * 2,
    height: 74,
    color: rgb(0.96, 0.98, 1),
    borderColor: sky,
    borderWidth: 1,
  });
  page.drawText("YOUR PAY FOR THIS LOAD", { x: M + 18, y: y - 6, size: 10, font: bold, color: gray });
  page.drawText(`$${rate.toLocaleString("en-US")}`, {
    x: M + 18,
    y: y - 44,
    size: 30,
    font: bold,
    color: navy,
  });
  y -= 96;

  // Stops
  page.drawText("Stops", { x: M, y, size: 13, font: bold, color: navy });
  y -= 22;
  const stops = load.stops || [];
  if (stops.length === 0) {
    page.drawText(`${load.originName || ""}  \u2192  ${load.destName || ""}`, {
      x: M,
      y,
      size: 11,
      font,
      color: navy,
    });
    y -= 18;
  } else {
    for (const s of stops) {
      const label = s.kind === "pickup" ? "Pickup" : "Delivery";
      const addr = (s.address || "").replace(/\s+/g, " ").slice(0, 74);
      const when = s.time ? `  (${String(s.time).slice(0, 28)})` : "";
      page.drawText(`${label}: ${addr}${when}`, { x: M, y, size: 10, font, color: navy });
      y -= 17;
      if (y < 90) break;
    }
  }

  // Footer
  page.drawText("Generated by LoadSprint", { x: M, y: 44, size: 8, font, color: gray });

  const bytes = await pdf.save();
  const b64 = Buffer.from(bytes).toString("base64");
  return `data:application/pdf;base64,${b64}`;
}
